### ISSUE TITLE
keyUp callback can be triggered erroneously

### ISSUE THREAD

**Issue by stevengoldberg** [stuartmemo/qwerty-hancock#17]
To reproduce:

1. Mousedown somewhere on the screen outside the keyboard element and hold down the mouse button.
2. Drag the cursor over the keyboard element and mouseup.

Fix:

Check for `mouse_is_down` in the `mouseUp` listener.

    var mouseUp = function (element, callback) {  
        if(!mouse_is_down) return;
        mouse_is_down = false;
        darkenDown(element);
        callback(element.title, getFrequencyOfNote(element.title));
    };

**Comment by stuartmemo** [comment]
Thanks for reporting, apologies for the late reply! This should be fixed in the latest release (0.4.5).
