### ISSUE TITLE
Keys become unaligned

### ISSUE THREAD

**Issue by ajgibbins** [stuartmemo/qwerty-hancock#18]
As the keyboard is built, key become gradually more misaligned. I have found a fix.

**Comment by stuartmemo** [comment]
Can give an example so I can recreate it?

**Comment by ajgibbins** [comment]
Hi Stuart.

Just create an instance with more than 1 octave and you'll see the problem.

I can tell you the resolution or submit you a gist.

I'm not at home right now but can attend to in the morning

Alex

**Comment by ajgibbins** [comment]
![screen shot 2015-08-03 at 09 38 18](https://cloud.githubusercontent.com/assets/623326/9033919/a4e62020-39c3-11e5-9846-eb51a5fab173.png)

**Comment by ajgibbins** [comment]
![screen shot 2015-08-03 at 09 41 11](https://cloud.githubusercontent.com/assets/623326/9033944/d8a612a8-39c3-11e5-9739-3a2f2a66feb2.png)

**Comment by stuartmemo** [comment]
I can't recreate this. Can you post your example html/js?

**Comment by ajgibbins** [comment]
I'm using it in Ionic / Cordova, so its a bit difficult. But I can post the
fix I've used.

Line 197 key.el.style.left = Math.floor((((white_key_width ) *
((key.noteNumber + 1 ) )  + 1 )- (black_key_width / 2))) + 'px';

Note how adding the 1 to white key width before multiplying it by
key.noteNumber + 1 will cause a cumulative offset to the right.

Modifying as above adds the 1px offset after the multiplication which
prevents cumulative shift.

Hope this helps clarify what I was experiencing.

Alex

**Comment by stuartmemo** [comment]
Cool, like I say I can't reproduce it, but will keep your fix in mind if it pops up again. Thanks!
