### ISSUE TITLE
'I' and '9' keys return NaN

### ISSUE THREAD

**Issue by abbernie** [stuartmemo/qwerty-hancock#19]
In the keyDown event listener 'frequency' is returned as 'NaN' for both 'I' and '9' keys, and 'note' is returned as 'Ch' for 'I' and 'C#h' for 9.

**Comment by stuartmemo** [comment]
I can't recreate this. 'l' returns `D4 293.6647679174076`, while the function doesn't get called for '9'.

Can you provide an example page? Any special keyboard layout?

**Comment by abbernie** [comment]
Apologies! I hadn't realized that my collaborator had edited the qwerty-hancock.js file and his change was the issue.
